version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: user
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: user
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: user_test

    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1

      - run:
          name: Install Bundle
          command: gem install bundler

      - run:
          name: Set bundle config path
          command: bundle config set path "vendor/bundle"

      - run:
          name: Set bundle config clean
          command: bundle config set clean "true"

      - run:
          name: Install gems
          command: bundle install

      - save_cache:
          key: gem-chace-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - restore_cache:
          keys:
            - yarn-chace-v1-{{ checksum "yarn.lock" }}
            - yarn-chace-v1-

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: yarn-chace-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: rubocop
          command: bundle exec rubocop -c .rubocop.yml

      - run:
          name: Lint
          command: |
            bundle exec slim-lint app/views -c .slim-lint.yml
            bin/yarn run lint:javascript

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Create DB
          command: bin/rails db:create

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Test
          command: bundle exec rspec

      - store_test_results:
          path: tmp/test-results
      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots
